MarketWeb/Models/ViewModels/Product.cs
using MarketWeb.Areas.Identity.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MarketWeb.Models.ViewModels
{
    public class Product
    {
        public int ProductID { get; set; }

        [Required]
        [Display(Name = "Product Name")]
        public string ProductName { get; set; }

        
        [Display(Name = "Image")]
        public string Image { get; set; }

        
        [Display(Name = "Self Start Date")]
        public DateTime SelfStartDate { get; set; }

        
        [Display(Name = "Self End Date")]
        public DateTime SelfEndDate { get; set; }

        [Required]
        [Display(Name = "Price")]
        public double Price { get; set; }

        [Required]
        [Display(Name = "User")]
        public string ApplicationUserId { get; set; }

        [Required]
        [Display(Name = "Category")]
        public int CategoryID { get; set; }

        [Required]
        [Display(Name = "Color")]
        public int ColorID { get; set; }

        [Required]
        [Display(Name = "Model")]
        public int ModelID { get; set; }

        [Required]
        [Display(Name = "Storage")]
        public int StorageID { get; set; }

        public ApplicationUser ApplicationUser { get; set; }

        public Category Category { get; set; }

        public Color Color { get; set; }

        public Model Model { get; set; }

        public Storage Storage { get; set; }

        public ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

MarketWeb/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MarketWeb.Models.ViewModels;
using MarketWeb.Models;
using Microsoft.AspNetCore.Http;

namespace MarketWeb.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IHttpContextAccessor _contextAccesor;

        public ProductsController(ApplicationDbContext context, IHttpContextAccessor contextAccessor)
        {
            _context = context;
            _contextAccesor = contextAccessor;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            if (_contextAccesor.HttpContext.Session.GetString("Cart") == null)
            {
                List<Cart> IsCart = new List<Cart>
                {
                    new Cart(_context.Products.Find(1), 1)
                };

                _contextAccesor.HttpContext.Session.SetObjectAsJson("Cart", IsCart);

                IsCart = _contextAccesor.HttpContext.Session.GetObjectFromJson<List<Cart>>("Cart");

                IsCart.RemoveAt(0);

                _contextAccesor.HttpContext.Session.SetObjectAsJson("Cart", IsCart);
            }

            var applicationDbContext = _context.Products.Include(p => p.ApplicationUser).Include(p => p.Category).Include(p => p.Color).Include(p => p.Model).Include(p => p.Storage);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.ApplicationUser)
                .Include(p => p.Category)
                .Include(p => p.Color)
                .Include(p => p.Model)
                .Include(p => p.Storage)
                .SingleOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["CategoryID"] = new SelectList(_context.Categorys, "CategoryID", "Name");
            ViewData["ColorID"] = new SelectList(_context.Colors, "ColorID", "Colors");
            ViewData["ModelID"] = new SelectList(_context.Models, "ModelID", "Models");
            ViewData["StorageID"] = new SelectList(_context.Storages, "StorageID", "Storages");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductID,ProductName,Image,SelfStartDate,SelfEndDate,Price,ApplicationUserId,CategoryID,ColorID,ModelID,StorageID")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", product.ApplicationUserId);
            ViewData["CategoryID"] = new SelectList(_context.Categorys, "CategoryID", "Name", product.CategoryID);
            ViewData["ColorID"] = new SelectList(_context.Colors, "ColorID", "Colors", product.ColorID);
            ViewData["ModelID"] = new SelectList(_context.Models, "ModelID", "Models", product.ModelID);
            ViewData["StorageID"] = new SelectList(_context.Storages, "StorageID", "Storages", product.StorageID);
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.SingleOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", product.ApplicationUserId);
            ViewData["CategoryID"] = new SelectList(_context.Categorys, "CategoryID", "Name", product.CategoryID);
            ViewData["ColorID"] = new SelectList(_context.Colors, "ColorID", "Colors", product.ColorID);
            ViewData["ModelID"] = new SelectList(_context.Models, "ModelID", "Models", product.ModelID);
            ViewData["StorageID"] = new SelectList(_context.Storages, "StorageID", "Storages", product.StorageID);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductID,ProductName,Image,SelfStartDate,SelfEndDate,Price,ApplicationUserId,CategoryID,ColorID,ModelID,StorageID")] Product product)
        {
            if (id != product.ProductID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", product.ApplicationUserId);
            ViewData["CategoryID"] = new SelectList(_context.Categorys, "CategoryID", "Name", product.CategoryID);
            ViewData["ColorID"] = new SelectList(_context.Colors, "ColorID", "Colors", product.ColorID);
            ViewData["ModelID"] = new SelectList(_context.Models, "ModelID", "Models", product.ModelID);
            ViewData["StorageID"] = new SelectList(_context.Storages, "StorageID", "Storages", product.StorageID);
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.ApplicationUser)
                .Include(p => p.Category)
                .Include(p => p.Color)
                .Include(p => p.Model)
                .Include(p => p.Storage)
                .SingleOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.SingleOrDefaultAsync(m => m.ProductID == id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductID == id);
        }
    }
}

MarketWeb/Controllers/ShoppingCartController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using MarketWeb.Models;
using System;
using MarketWeb.Models.ViewModels;

namespace MarketWeb.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IHttpContextAccessor _contextAccesor;

        private string strCart = "Cart";

        private List<Cart> IsCart;


        public ShoppingCartController(ApplicationDbContext context, IHttpContextAccessor contextAccessor)
        {
            _context = context;
            _contextAccesor = contextAccessor;

        }


        public IActionResult Index()
        {
            return View();
        }


        
        public IActionResult OrderNow(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (_contextAccesor.HttpContext.Session.GetString(strCart) == null)
            {
                IsCart = new List<Cart>
                {
                    new Cart(_context.Products.Find(id), 1)
                };

                _contextAccesor.HttpContext.Session.SetObjectAsJson(strCart, IsCart);
            }

            else
            {
                IsCart = _contextAccesor.HttpContext.Session.GetObjectFromJson<List<Cart>>(strCart);

                int check = IsExistingCheck(id);

                if (check == -1)
                {
                    IsCart.Add(new Cart(_context.Products.Find(id), 1));
                }
                else
                {
                    IsCart[check].Quantity++;
                }

                _contextAccesor.HttpContext.Session.SetObjectAsJson(strCart, IsCart);
            }
            return View("Index");
        }


        private int IsExistingCheck(int? id)
        {
            IsCart = _contextAccesor.HttpContext.Session.GetObjectFromJson<List<Cart>>(strCart);

            for (int i = 0; i < IsCart.Count; i++)
            {
                if (IsCart[i].Product.ProductID == id) return i;
            }

            return -1;
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            IsCart = _contextAccesor.HttpContext.Session.GetObjectFromJson<List<Cart>>(strCart);

            int check = IsExistingCheck(id);


            IsCart.RemoveAt(check);

            _contextAccesor.HttpContext.Session.SetObjectAsJson(strCart, IsCart);

            return RedirectToAction("Index");
        }


        public IActionResult UpdateCart()
        {
            string[] quantities = _contextAccesor.HttpContext.Request.Form["quantity"];

            IsCart = _contextAccesor.HttpContext.Session.GetObjectFromJson<List<Cart>>(strCart);

            for (int i = 0; i < IsCart.Count; i++)
            {
                IsCart[i].Quantity = Convert.ToInt32(quantities[i]);
            }

            _contextAccesor.HttpContext.Session.SetObjectAsJson(strCart, IsCart);

            return RedirectToAction("Index");
        }


        public ActionResult CheckOut()
        {

            return View("CheckOut");
        }

        public ActionResult ProcessOrder(IFormCollection frc)
        {
            IsCart = _contextAccesor.HttpContext.Session.GetObjectFromJson<List<Cart>>(strCart);

            Order order = new Order()
            {
                CustomerName = frc["cusName"],
                CustomerPhone = frc["cusPhone"],
                CustomerEmail = frc["cusEmail"],
                CustomerAddress = frc["cusAddress"],
                OrderDate = DateTime.Now,
                PaymentType = "Cash",
                Status = "Processing"
            };
            _context.Orders.Add(order);
            _context.SaveChanges();


            foreach (var cart in IsCart)
            {
                OrderDetail orderDetail = new OrderDetail()
                {
                    OrderID = order.OrderID,
                    ProductID = cart.Product.ProductID,
                    Quantity = cart.Quantity,
                    Price = cart.Product.Price
                };
                _context.OrderDetails.Add(orderDetail);
                _context.SaveChanges();
            }


            _contextAccesor.HttpContext.Session.Remove(strCart);

            return View("OrderSuccess");
        }
    }
}

MarketWeb/Views/Products/Create.cshtml
@model MarketWeb.Models.ViewModels.Product

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="ProductName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Image" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SelfStartDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SelfStartDate" class="form-control" />
                <span asp-validation-for="SelfStartDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SelfEndDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SelfEndDate" class="form-control" />
                <span asp-validation-for="SelfEndDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ApplicationUserId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="ApplicationUserId" class ="form-control" asp-items="ViewBag.ApplicationUserId"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CategoryID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="CategoryID" class ="form-control" asp-items="ViewBag.CategoryID"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ColorID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="ColorID" class ="form-control" asp-items="ViewBag.ColorID"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ModelID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="ModelID" class ="form-control" asp-items="ViewBag.ModelID"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="StorageID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="StorageID" class ="form-control" asp-items="ViewBag.StorageID"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MarketWeb/Views/Products/Delete.cshtml
@model MarketWeb.Models.ViewModels.Product

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="ProductID" />
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SelfStartDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SelfStartDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SelfEndDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SelfEndDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Color.Colors)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Model.Models)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Storage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Storage.Storages)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

MarketWeb/Views/Products/Details.cshtml
@model MarketWeb.Models.ViewModels.Product

@{
    ViewData["Title"] = "Details";
}

<h1>PRODUCT DETAILS</h1>

<hr />

<div>

    <hr />

    <div class="row">
        <div class="col-md-4">
            <img src="~/images/@Model.Image" style="width:260px;height:260px" />
        </div>

        <div class="col-md-4">
            <div class="row"><h1>@Model.ProductName</h1></div>
            <div class="row"><h1 style="color:red">Price: $@Model.Price</h1></div>
            <div class="row"><h3>@Html.ActionLink("Add to Cart", "OrderNow", "ShoppingCart", new { id = Model.ProductID }, null)</h3></div>
        </div>

    </div>

</div>
<hr />
<div>
    <a asp-action="Edit" asp-route-id="@Model.ProductID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MarketWeb/Views/Products/Edit.cshtml
@model MarketWeb.Models.ViewModels.Product

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ProductID" />
        <div class="form-group">
            <label asp-for="ProductName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Image" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SelfStartDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SelfStartDate" class="form-control" />
                <span asp-validation-for="SelfStartDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SelfEndDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SelfEndDate" class="form-control" />
                <span asp-validation-for="SelfEndDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ApplicationUserId" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="ApplicationUserId" class="form-control" asp-items="ViewBag.ApplicationUserId"></select>
                <span asp-validation-for="ApplicationUserId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CategoryID" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="CategoryID" class="form-control" asp-items="ViewBag.CategoryID"></select>
                <span asp-validation-for="CategoryID" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ColorID" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="ColorID" class="form-control" asp-items="ViewBag.ColorID"></select>
                <span asp-validation-for="ColorID" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ModelID" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="ModelID" class="form-control" asp-items="ViewBag.ModelID"></select>
                <span asp-validation-for="ModelID" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="StorageID" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="StorageID" class="form-control" asp-items="ViewBag.StorageID"></select>
                <span asp-validation-for="StorageID" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MarketWeb/Views/Products/Index.cshtml
@model IEnumerable<MarketWeb.Models.ViewModels.Product>
@using MarketWeb.Respository
@inject ICartRespository CartRespository


@{
    ViewData["Title"] = "Index";
}

<h2>Shopping Online - Get Reward</h2>




<div class="div-container">

    <div class="clear"></div>
    <div class="div-left">
        <div class="category-title">Category</div>
        <div class="category-list">
            <ul>
                <li><a href="#">Iphone</a></li>
                <li><a href="#">Ipad</a></li>
                <li><a href="#">Mac</a></li>
            </ul>
        </div>
    </div>
    <div class="div-main">
        @foreach (var items in Model)
         {
            <div class="main-content">
                <div class="content-image">
                    <a asp-action="Details" asp-route-id="@items.ProductID">
                        <img src="~/images/@items.Image" />
                    </a>
                </div>
                <div class="content-title">
                    <a asp-action="Details" asp-route-id="@items.ProductID">@items.ProductName</a>
                </div>
                <div class="content-price">
                    Price: $@items.Price
                </div>
                @*<div class="content-price">
                        @Html.ActionLink("Add to Cart", "OrderNow", "ShoppingCart", new { id = items.ProductID }, null)
                    </div>*@
                <div class="content-price">
                    <a role="button" class="btn btn-default @(CartRespository.IsExistingCheck(@items.ProductID) ? "disabled" : "")" onclick="modifyTitle(@items.ProductID)">
                       <span id="divloader" style="display:none;"><img src="~/images/Eclipse-1s-200px.gif" width="30px" height="30px" alt="Loader"/></span> @(CartRespository.IsExistingCheck(@items.ProductID) ? "Product Already exists in Cart" : "Add to Cart")
                    </a>
                </div>
            </div>
         }


            <div class="clear"></div>
            <div class="div-footer">
                <p>Copyright 2018 Fela Baba</p>
            </div>
        </div>
    </div>